"""Documents center [EXT]. Presigned POST upload -> /complete verification -> download via presigned GET.

``validate_resume_document`` is the reusable check other modules (applications, students) call.
"""

import logging
import re
import uuid
from typing import Any

from sqlalchemy import update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.base import utcnow
from app.core.config import settings
from app.core.errors import AppError, conflict, not_found, unprocessable
from app.core.pagination import PageParams, make_page, paginate
from app.core.permissions import owned_internship_ids
from app.core.side_effects import audit, notify
from app.core.storage import DOWNLOAD_TTL_SECONDS, UPLOAD_TTL_SECONDS, Storage
from app.core.types import MAX_RESUME_BYTES
from app.core.validators import is_pdf_magic
from app.modules.documents import repository as repo
from app.modules.documents import schemas as s
from app.modules.documents.models import Document as DocumentModel
from app.modules.students.models import Student
from app.modules.users.models import User

log = logging.getLogger(__name__)

PDF = "application/pdf"
MAX_UPLOAD_BYTES = MAX_RESUME_BYTES  # 5 MB for every kind
# Kinds a user may upload themselves (REPORT / EXPORT are generated by workers)
UPLOADABLE_KINDS = {"RESUME", "COVER_LETTER", "TRANSCRIPT", "OFFER_LETTER", "LOGO", "IMPORT", "OTHER"}
LOGO_TYPES = {"image/png", "image/jpeg", "image/webp", "image/gif"}
OTHER_ALLOWED_TYPES = LOGO_TYPES | {
    PDF,
    "text/plain",
    "text/csv",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}


def _err_code(kind: str) -> str:
    return "RESUME_INVALID" if kind == "RESUME" else "VALIDATION_ERROR"


def bucket_for(kind: str) -> str:
    return settings.BUCKET_RESUMES if kind == "RESUME" else settings.BUCKET_DOCUMENTS


def slugify_filename(filename: str) -> str:
    name = filename.replace("\\", "/").rsplit("/", 1)[-1]
    stem, dot, ext = name.rpartition(".")
    if not dot:
        stem, ext = name, ""
    stem = re.sub(r"[^A-Za-z0-9_-]+", "-", stem).strip("-_")[:80] or "file"
    ext = re.sub(r"[^A-Za-z0-9]", "", ext).lower()[:10]
    return f"{stem}.{ext}" if ext else stem


def to_out(doc: DocumentModel, owner_name: str, in_use: bool) -> s.Document:
    return s.Document(
        id=doc.id,
        kind=doc.kind,
        filename=doc.filename,
        content_type=doc.content_type,
        size_bytes=doc.size_bytes,
        status=doc.status,
        verification_status=doc.verification_status,
        created_at=doc.created_at,
        owner=s.DocumentOwner(id=doc.owner_id, full_name=owner_name),
        verification_note=doc.verification_note,
        verified_at=doc.verified_at,
        in_use=in_use,
    )


async def _out(session: AsyncSession, document_id: uuid.UUID) -> s.Document:
    row = await repo.get_row(session, document_id)
    if row is None:
        raise not_found("Document not found")
    return to_out(*row)


# ---- reusable validation (applications / students) --------------------------------------------------------
async def validate_resume_document(
    session: AsyncSession, student_id: uuid.UUID, document_id: uuid.UUID | None
) -> DocumentModel:
    """Ensure ``document_id`` is a usable resume for ``student_id`` (owner, kind RESUME, UPLOADED, PDF, <= 5 MB).

    Raises ``AppError`` 422 ``RESUME_REQUIRED`` when ``document_id`` is None, 422 ``RESUME_INVALID`` otherwise.
    Documents that belong to someone else are reported as RESUME_INVALID (never reveals they exist).
    """
    if document_id is None:
        raise unprocessable(
            "A PDF resume is required",
            "RESUME_REQUIRED",
            [{"field": "resume_document_id", "message": "A PDF resume is required"}],
        )
    doc = await repo.get(session, document_id)

    def bad(msg: str) -> AppError:
        return unprocessable(msg, "RESUME_INVALID", [{"field": "resume_document_id", "message": msg}])

    if doc is None or doc.owner_id != student_id:
        raise bad("Resume document not found")
    if doc.kind != "RESUME":
        raise bad("The selected document is not a resume")
    if doc.status != "UPLOADED":
        raise bad("The resume upload has not been completed")
    if doc.content_type != PDF:
        raise bad("Resume must be a PDF")
    if doc.size_bytes > MAX_RESUME_BYTES:
        raise bad("Resume must be 5 MB or smaller")
    return doc


# ---- upload flow -------------------------------------------------------------------------------------------
async def create_upload_url(
    session: AsyncSession, storage: Storage, user: User, data: s.UploadUrlRequest
) -> s.UploadTicket:
    kind = data.kind.value
    content_type = data.content_type.split(";")[0].strip().lower()
    if kind not in UPLOADABLE_KINDS:
        raise unprocessable(
            f"Documents of kind {kind} cannot be uploaded", details=[{"field": "kind", "message": "Not allowed"}]
        )
    if kind == "RESUME" and content_type != PDF:
        raise unprocessable(
            "Resume must be a PDF file",
            "RESUME_INVALID",
            [{"field": "content_type", "message": "Only application/pdf is accepted for resumes"}],
        )
    if kind == "LOGO" and content_type not in LOGO_TYPES:
        raise unprocessable(
            "Logo must be an image",
            details=[{"field": "content_type", "message": "Only PNG, JPEG, WebP or GIF images are accepted"}],
        )
    if kind != "RESUME" and content_type not in OTHER_ALLOWED_TYPES:
        raise unprocessable(
            "Unsupported file type",
            details=[{"field": "content_type", "message": f"{content_type} is not supported"}],
        )
    if data.size_bytes > MAX_UPLOAD_BYTES:
        raise unprocessable(
            "File must be 5 MB or smaller",
            "FILE_TOO_LARGE",
            [{"field": "size_bytes", "message": "Maximum file size is 5 MB (5242880 bytes)"}],
        )

    doc_id = uuid.uuid4()
    bucket = bucket_for(kind)
    key = f"{user.id}/{doc_id}/{slugify_filename(data.filename)}"
    doc = DocumentModel(
        id=doc_id,
        owner_id=user.id,
        kind=kind,
        bucket=bucket,
        object_key=key,
        filename=data.filename[:255],
        content_type=content_type,
        size_bytes=data.size_bytes,
        status="PENDING_UPLOAD",
        verification_status="PENDING",
    )
    session.add(doc)
    await session.flush()
    ticket = await storage.presign_post(bucket, key, content_type, MAX_UPLOAD_BYTES, UPLOAD_TTL_SECONDS)
    audit(session, user, "document.upload_url", "document", doc.id, after={"kind": kind, "filename": doc.filename})
    return s.UploadTicket(
        document_id=doc.id,
        upload=s.UploadTarget(url=ticket["url"], fields=ticket["fields"]),
        expires_in=UPLOAD_TTL_SECONDS,
        max_bytes=MAX_UPLOAD_BYTES,
    )


async def _reject_upload(
    session: AsyncSession, storage: Storage, user: User, doc: DocumentModel, reason: str, code: str
) -> None:
    """Persist REJECTED (the request transaction would otherwise roll back), delete the object, raise 422."""
    try:
        await storage.delete(doc.bucket, doc.object_key)
    except Exception:  # noqa: BLE001 - best effort
        log.exception("could not delete rejected object %s", doc.object_key)
    doc.status = "REJECTED"
    audit(session, user, "document.reject_upload", "document", doc.id, after={"reason": reason})
    await session.commit()
    raise AppError(422, code, reason, [{"field": "file", "message": reason}])


async def complete_upload(session: AsyncSession, storage: Storage, user: User, document_id: uuid.UUID) -> s.Document:
    doc = await repo.get(session, document_id)
    if doc is None or doc.owner_id != user.id:
        raise not_found("Document not found")
    if doc.status == "UPLOADED":
        return await _out(session, doc.id)  # idempotent
    if doc.status == "REJECTED":
        raise conflict("This upload was rejected. Request a new upload URL.")

    code = _err_code(doc.kind)
    head = await storage.head(doc.bucket, doc.object_key)
    if head is None:
        raise unprocessable(
            "The file has not been uploaded yet", code, [{"field": "file", "message": "File not found in storage"}]
        )
    size = int(head["size"])
    if size > MAX_UPLOAD_BYTES:
        await _reject_upload(session, storage, user, doc, "File must be 5 MB or smaller", "FILE_TOO_LARGE")
    if size != doc.size_bytes:
        await _reject_upload(session, storage, user, doc, "Uploaded file size does not match the declared size", code)
    stored_type = (head.get("content_type") or "").split(";")[0].strip().lower()
    if doc.content_type == PDF:
        if stored_type and stored_type != PDF:
            await _reject_upload(session, storage, user, doc, "File must be a PDF", code)
        magic = await storage.read_range(doc.bucket, doc.object_key, 0, 4)
        if not is_pdf_magic(magic):
            await _reject_upload(session, storage, user, doc, "File is not a valid PDF", code)

    doc.status = "UPLOADED"
    await session.flush()
    audit(session, user, "document.upload", "document", doc.id, after={"kind": doc.kind, "size_bytes": size})
    return await _out(session, doc.id)


# ---- queries -----------------------------------------------------------------------------------------------
async def list_documents(
    session: AsyncSession,
    user: User,
    params: PageParams,
    kind: str | None,
    owner_id: uuid.UUID | None,
    verification_status: str | None,
    status: str | None,
) -> dict[str, Any]:
    stmt = repo.rows_query()
    if user.role == "ADMIN":
        if owner_id:
            stmt = stmt.where(DocumentModel.owner_id == owner_id)
    else:
        stmt = stmt.where(DocumentModel.owner_id == user.id)
        if owner_id and owner_id != user.id:
            stmt = stmt.where(DocumentModel.id.is_(None))  # outside scope -> empty
    if kind:
        stmt = stmt.where(DocumentModel.kind == kind)
    if verification_status:
        stmt = stmt.where(DocumentModel.verification_status == verification_status)
    stmt = stmt.where(DocumentModel.status == (status or "UPLOADED"))  # hide abandoned/rejected uploads by default
    stmt = stmt.order_by(DocumentModel.created_at.desc(), DocumentModel.id)
    rows, total = await paginate(session, stmt, params, scalars=False)
    return make_page([to_out(r[0], r[1], bool(r[2])) for r in rows], total, params)


async def download_url(session: AsyncSession, storage: Storage, user: User, document_id: uuid.UUID) -> s.DownloadUrl:
    doc = await repo.get(session, document_id)
    if doc is None:
        raise not_found("Document not found")
    allowed = user.role == "ADMIN" or doc.owner_id == user.id
    if not allowed and user.role in ("FACULTY", "COMPANY"):
        owned = await owned_internship_ids(session, user)
        allowed = await repo.targets_owned_internship(session, doc.id, owned)
    if not allowed:
        raise not_found("Document not found")
    if doc.status != "UPLOADED":
        raise conflict("The document upload has not been completed")
    url = await storage.presign_get(doc.bucket, doc.object_key, doc.filename, DOWNLOAD_TTL_SECONDS)
    return s.DownloadUrl(url=url, expires_in=DOWNLOAD_TTL_SECONDS)


async def delete_document(session: AsyncSession, storage: Storage, user: User, document_id: uuid.UUID) -> None:
    doc = await repo.get(session, document_id)
    if doc is None or (doc.owner_id != user.id and user.role != "ADMIN"):
        raise not_found("Document not found")
    row = await repo.get_row(session, doc.id)
    if row is not None and row[2]:
        raise conflict("This document is attached to an active application", "IN_USE")
    referenced = await repo.is_referenced(session, doc.id)
    # students whose default resume this is fall back to "no default"
    await session.execute(update(Student).where(Student.default_resume_id == doc.id).values(default_resume_id=None))
    doc.deleted_at = utcnow()
    await session.flush()
    audit(session, user, "document.delete", "document", doc.id, before={"kind": doc.kind, "filename": doc.filename})
    if not referenced:  # keep the object when an old (withdrawn) application still points at it
        try:
            await storage.delete(doc.bucket, doc.object_key)
        except Exception:  # noqa: BLE001 - best effort
            log.exception("could not delete object %s", doc.object_key)


async def set_verification(
    session: AsyncSession, admin: User, document_id: uuid.UUID, data: s.VerificationRequest
) -> s.Document:
    doc = await repo.get(session, document_id)
    if doc is None:
        raise not_found("Document not found")
    if doc.status != "UPLOADED":
        raise conflict("Only uploaded documents can be verified")
    before = {"verification_status": doc.verification_status, "note": doc.verification_note}
    doc.verification_status = data.verification_status
    doc.verification_note = data.note
    if data.verification_status == "PENDING":
        doc.verified_by, doc.verified_at = None, None
    else:
        doc.verified_by, doc.verified_at = admin.id, utcnow()
    await session.flush()
    audit(
        session,
        admin,
        "document.verify",
        "document",
        doc.id,
        before=before,
        after={"verification_status": doc.verification_status, "note": doc.verification_note},
    )
    if data.verification_status != "PENDING" and doc.owner_id != admin.id:
        verdict = "verified" if data.verification_status == "VERIFIED" else "rejected"
        notify(
            session,
            doc.owner_id,
            "SYSTEM",
            f"Document {verdict}",
            f"Your document {doc.filename} was {verdict}." + (f" Note: {data.note}" if data.note else ""),
            "/documents",
            {"document_id": str(doc.id), "verification_status": doc.verification_status},
        )
    return await _out(session, doc.id)
